# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01a01e68aa07e0cb3113894fd045e7e115e61905e87447e4c935f52c030175248bfe5beb699c41fb8de08cbe284a951e67267e0884a75e404a27d1318e795b68

test:
  secret_key_base: ec6497344e28d2c23757f10b8093d5b552d71a45d6c52cedcb07697852cce15d61f83e02a48de2cad68513defd76b178ec1a7752d03c9236126c2f38b317b71f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
